# Generated by Django 4.1.7 on 2026-03-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='team',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='team_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='team_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workout',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
